version: '3'
services:

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pinsanity
      - POSTGRES_PASSWORD=pinsanity
      - POSTGRES_DB=pinsanity
    #network_mode: host

  backend:
    container_name: backend
    build: ./backend/
    restart: always
    ports:
     - "8080:8080"
    environment:
     # Vite takes care of most of this for us, but it's good practice for other backends
     - VITE_DB_HOST=postgres
     - VITE_IP_ADDR=0.0.0.0
     - VITE_PORT=8080
     - VITE_LOGS_DIR=logs/
     - VITE_DB_PORT=5432
     - VITE_DB_USER=pinsanity
     - VITE_DB_PASS=pinsanity
     - VITE_DB_NAME=postgres
     - VITE_MINIO_HOST=minio
     - VITE_MINIO_PORT=9000
     - VITE_MINIO_USER=minioUser
     - VITE_MINIO_PASS=minioPass
     - VITE_AUTH_DOMAIN=dev-3bjmrn5j71aoqrhy.us.auth0.com
     - VITE_AUTH_CLIENT=W03dWCj9CvwnamvjgAiAGCtWbjfoqr5r
     - VITE_AUTH_SECRET=V3kS8N0dbs4CrwfQmnjUrim0VmAKOJ0w68pG8KliByJuBGeE1lnos78dGah4tW4L
    depends_on:
     - postgres
  
  frontend:
    container_name: frontend
    build: ./frontend/
    restart: always
    ports:
      #- "88:80" # We need to map here for convenience, so we don't conflict with a potential possible local server
      - "1138:80"
    environment:
      - VITE_BACKEND_IP=backend
      - VITE_BACKEND_PORT=8080

  minio:
    container_name: minio
    image: docker.io/bitnami/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_DEFAULT_BUCKETS=pinsanity:public
      - MINIO_ROOT_USER=minioUser
      - MINIO_ROOT_PASSWORD=minioPass
      - MINIO_SERVER_ACCESS_KEY=minioUser
      - MINIO_SERVER_SECRET_KEY=minioPass
    volumes:
      - minio_data:/data

volumes:
  minio_data:
    driver: local
  db:
    driver: local
